# syntax=docker/dockerfile:1

FROM gcr.io/distroless/cc-debian13@sha256:9b615fff20e1a4fad29c2b30562580b212c7dd5e2225236735cca0070ed11c78

ARG TARGETARCH
ARG VERSION
ARG REVISION

LABEL org.opencontainers.image.source="https://github.com/rvben/yamldap" \
      org.opencontainers.image.description="YAML-backed LDAP server" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.version="$VERSION" \
      org.opencontainers.image.revision="$REVISION"

COPY --chmod=755 artifacts/yamldap-linux-${TARGETARCH}/yamldap /yamldap

EXPOSE 1389

USER 65532:65532

ENTRYPOINT ["/yamldap"]
